### ISSUE TITLE
Connection not working

### ISSUE THREAD

**Issue by vlucki** [qualisys/QTM-Connect-For-Unreal#1]
Hey there!

I've been trying to get this working but the available documentation has not been kind to me.

I tried on unreal 4.20, compiling and fixing the issues that popped up myself, and 4.18. 

In both cases, I managed to get the client and rigid body component on unreal without a problem, but once I press play nothing happens. 

We managed to get it working with motion builder, so at least the system is running correctly.

can anyone offer some advice as how to get UE to cooperate? Perhaps done more in depth instructions? Both on the unreal and QTM side?

Any help is appreciated.

**Comment by mlveggo** [comment]
Hi,

Have you defined the rigid body in QTM and use the exact same name in the Unreal rigid body component?

Are you streaming realtime data (running QTM live / capture), or are you streaming from file (Play with realtime output)? Start QTM streaming before pressing play in Unreal.

We're working on bringing the UE version up to 4.19 and 4.20.

Best regards,
Morgan.Larsson@qualisys.se

**Comment by blkVlucki** [comment]
We were trying out the realtime connection. I do believe everything was up and running as it should, but one thing I noticed on later tests is that the object with the rigidbody was not set to movable at one point, so it worked after setting it properly.

This may have been the issue before, since we got it to work.

The only difficulty we are having now is understanding how the system works we dealing with many joints - say a fully rigged character. But that's already another topic, so I guess we can close this issue.

Thanks for the support, and we look forward to the updated versions of the plugin.
