### ISSUE TITLE
hi, what's the data format sending to QTMLivelink plugin?

### ISSUE THREAD

**Issue by lucasjinreal** [qualisys/QTM-Connect-For-Unreal#57]
hi, this seems a useful work, i want sending the skeleton animation from python, but didn't know what's the data format does QTMLivelink need, does there any doc about this?

**Comment by EmilRosenquist** [comment]
Hi @jinfagang, The information to get started is in the README. For streaming skeleton you should start with getting QTM and QTMLiveLinkPlugin running see [here ](https://github.com/qualisys/QTM-Connect-For-Unreal/blob/master/README.md#start-live-link-source) and then for getting an skeleton, see [here ](https://github.com/qualisys/QTM-Connect-For-Unreal/blob/master/README.md#stream-skeleton-data).
Here is a tutorial video showing the processs https://www.youtube.com/watch?v=lJ3CwEu2OxY.

Regarding sending skeleton animation data from python is not possible. Since the plugin works with an real time connection to QTM.
